### ISSUE TITLE
Getting the following error

### ISSUE THREAD

**Issue by angelomendonca** [ceumicrodata/mETL#31]
Error in buffer element. Not sure why this occurs but seems like the connection.execute is not able to do it.

**Comment by bfaludi** [comment]
You get this error when you can not write every record to the database. Usually there is a `NULL` value in your dataset which is not allowed or one of your map is not defined correctly. If you want to ignore this mechanism you can add the `continueOnError: true` attribute to your `target` and you will get a list of every ignored line.

**Comment by angelomendonca** [comment]
Mr Faludi, thank you for your answer. I fixed the issue. I had a DB table set to NN and it was sending a null value in the sql Insert.

**Comment by angelomendonca** [comment]
Hi Bence, Can we transform one csv file to more than one table? Like split
the file into one parent table and the other a child table using metl?
